resolver 127.0.0.11 valid=10s ipv6=off;

upstream devops-project_app {
    zone devops_project_app 64k;
    server web1:80 resolve max_fails=2 fail_timeout=10s;
    server web2:80 resolve max_fails=2 fail_timeout=10s;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 20m;

    location / {
        proxy_pass http://devops-project_app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
}
