apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-project-config
  namespace: devops-project
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: gestion_demandes
  BASE_URL: /devops-project
  APP_BASE_URL: http://devops-project.local
