apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-project

# Image mise à jour automatiquement par Jenkins (sed)
# Jenkins exécute : sed -i 's|image: devops-project-web:.*|image: ${ECR_REPO}:${IMAGE_TAG}|g' kustomization.yaml
images:
  - name: devops-project-web
    newTag: latest

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - efs-storage.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app: devops-project
  managed-by: terraform