apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-project

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - efs-storage.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml