apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - uploads-pvc.yaml
  - mysql.yaml
  - app-frontend.yaml
  - app-backend.yaml
  - ingress.yaml
  - monitoring.yaml
  - jenkins.yaml
