apiVersion: v1
kind: Secret
metadata:
  name: devops-project-secret
  namespace: devops-project
type: Opaque
stringData:
  DB_USER: "app"
  DB_PASS: "CHANGE_ME_SECURE_PASSWORD"
  DB_ROOT_PASSWORD: "CHANGE_ME_ROOT_PASSWORD"