apiVersion: v1
kind: Secret
metadata:
  name: devops-project-secret
  namespace: devops-project
type: Opaque
stringData:
  DB_USER: "dev_user"
  DB_PASS: "dev_pass_123"
  DB_ROOT_PASSWORD: "root_pass_123"
